services:
  postgresql:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data/'

  keycloak:
    build:
      dockerfile: ./build/Dockerfile
    depends_on:
      - postgresql
    ports:
      - "5080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: "start-dev"

  dest-app:
    image: nginx
    ports:
      - "5081:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./demo/dest-app:/usr/share/nginx/html

  start-app:
    image: nginx
    ports:
      - "5082:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./demo/start-app:/usr/share/nginx/html

volumes:
  postgresql_data:
    driver: local
